Repository nscv/lotte-kurly, pull requests merged in 2022-07, with the labels that each got.

#22 chore: RDS 연동 확인 #14
  pom.xml
  src/main/java/com/lotte/db/DBTestController.java
  src/main/java/com/lotte/db/dao/DBTestDao.java
  src/main/java/com/lotte/db/service/DBTestService.java
  src/main/java/com/lotte/db/vo/DBTestVO.java
  src/main/resources/sqls/DBTestVO.xml
  src/test/java/com/lotte/db/DBTestServiceTest.java
Labels: 💻 chore

#23 상품 등록 및 재고 업데이트 #10
  src/main/java/com/lotte/products/controller/ProductController.java
  src/main/java/com/lotte/products/controller/TempController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/dto/ProductDto.java
  src/main/java/com/lotte/products/dto/TempDto.java
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/java/com/lotte/products/service/TempService.java
  src/main/resources/sqls/product.xml
Labels: 👾 feat

#32 feat : crawling 일부 작업 완료 #31
  src/main/java/com/lotte/crawling/controller/CrawlingController.java
  src/main/java/com/lotte/crawling/dao/CrawlingDao.java
  src/main/java/com/lotte/crawling/dto/CrawlingDto.java
  src/main/java/com/lotte/crawling/service/CrawlingService.java
  src/main/resources/sqls/Crawling.xml
  src/main/webapp/WEB-INF/views/crawling.jsp
Labels: 👾 feat

#37 hotfix: 유저컨트롤러, 프로덕트리스트
  src/main/java/com/lotte/products/controller/ProductController.java
  src/main/java/com/lotte/users/controller/UserController.java
  src/main/java/com/lotte/users/service/UserService.java
  target/lotte_kurly/META-INF/MANIFEST.MF
  target/lotte_kurly/index.jsp
Labels: 🚨 hotfix

#33 통계 기능 구현
  src/main/Test/com/lotte/products/controller/StatisticControllerTest.java
  src/main/java/com/lotte/products/controller/ProductController.java
  src/main/java/com/lotte/products/controller/StatisticController.java
  src/main/java/com/lotte/products/dao/StatisticDao.java
  src/main/java/com/lotte/products/dto/ProductCategoryDto.java
  src/main/java/com/lotte/products/dto/ProductDto.java
  src/main/java/com/lotte/products/dto/UserAgeDto.java
  src/main/java/com/lotte/products/dto/UserGenderDto.java
  src/main/java/com/lotte/products/dto/UserGradeDto.java
  src/main/java/com/lotte/products/service/StatisticService.java
  src/main/java/com/lotte/products/service/StatisticServiceImpl.java
  src/main/resources/sqls/Product.xml
  src/main/resources/sqls/Statistic.xml
  src/main/webapp/WEB-INF/views/admin/test.jsp
Labels: 👾 feat

#42 controller와 restcontroller 분리 및 스프링 빈 주입 방식 변경
  src/main/java/com/lotte/products/controller/ProductController.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/controller/StatisticController.java
  src/main/java/com/lotte/products/dto/ProductDto.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/java/com/lotte/products/service/StatisticServiceImpl.java
  src/main/resources/sqls/Product.xml
Labels: 🌻 refactor

#44 Feat/productlist
  pom.xml
  src/main/java/com/lotte/products/controller/ProductController.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/product/productlist.jsp
  src/main/webapp/front/header.jsp
  target/lotte_kurly/META-INF/MANIFEST.MF
  target/lotte_kurly/front/header.jsp
Labels: 👾 feat

#47 feat : crawling Category Product Product_img 완료 #31
  src/main/java/com/lotte/crawling/controller/CrawlingController.java
  src/main/java/com/lotte/crawling/dao/CrawlingDao.java
  src/main/java/com/lotte/crawling/dto/CrawlingCategoryDto.java
  src/main/java/com/lotte/crawling/dto/CrawlingDto.java
  src/main/java/com/lotte/crawling/service/CrawlingService.java
  src/main/java/com/lotte/crawling/service/CrawlingServiceImpl.java
  src/main/java/com/lotte/products/dto/ProductDto.java
  src/main/java/com/lotte/products/dto/ProductImgDto.java
  src/main/java/com/lotte/products/dto/categoriesDto.java
  src/main/resources/sqls/Crawling.xml
  src/main/webapp/WEB-INF/views/crawling/crawling.jsp
Labels: 👾 feat

#50 Feat/admin statistic #21
  src/main/java/com/lotte/products/controller/ProductController.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/controller/StatisticController.java
  src/main/java/com/lotte/products/dto/ProductCategoryDto.java
  src/main/resources/sqls/Statistic.xml
  src/main/webapp/WEB-INF/views/admin/age-graph.jsp
  src/main/webapp/WEB-INF/views/admin/axis.jsp
  src/main/webapp/WEB-INF/views/admin/donut.jsp
  src/main/webapp/WEB-INF/views/admin/gender-graph.jsp
Labels: 👾 feat

#54 feat : 쿠키를 사용하여 오늘 본 상품 구현 수정 #53
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/dto/ProductListDto.java
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/WEB-INF/views/product/productlist.jsp
  src/main/webapp/front/header.jsp
  target/lotte_kurly/front/header.jsp
Labels: 👾 feat

#52 feat: 상품 결제 #51
  pom.xml
  src/main/java/com/lotte/accounts/controller/AccountController.java
  src/main/java/com/lotte/accounts/controller/TempController.java
  src/main/java/com/lotte/accounts/dao/AccountDao.java
  src/main/java/com/lotte/accounts/dao/TempDao.java
  src/main/java/com/lotte/accounts/dto/AccountDto.java
  src/main/java/com/lotte/accounts/dto/TempDto.java
  src/main/java/com/lotte/accounts/service/AccountService.java
  src/main/java/com/lotte/accounts/service/AccountServiceImpl.java
  src/main/java/com/lotte/accounts/service/TempService.java
  src/main/java/com/lotte/orders/dto/OrderProductsDto.java
  src/main/java/com/lotte/products/controller/ProductController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/dto/ProductListDto.java
  src/main/resources/sqls/Account.xml
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/admin/test.jsp
  src/test/java/com/lotte/accounts/controller/AccountControllerTest.java
  target/lotte_kurly/META-INF/MANIFEST.MF
Labels: 👾 feat

#57 Feat/productlist #56
  src/main/java/com/lotte/categories/controller/CategoryController.java
  src/main/java/com/lotte/categories/dao/CategoryDao.java
  src/main/java/com/lotte/categories/dto/CategoryDto.java
  src/main/java/com/lotte/categories/service/CategoryService.java
  src/main/java/com/lotte/categories/service/CategoryServiceImpl.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/dto/ProductDto.java
  src/main/java/com/lotte/products/dto/ProductListDto.java
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/resources/sqls/Category.xml
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/WEB-INF/views/product/productlist.jsp
  src/main/webapp/front/header.jsp
  target/lotte_kurly/front/header.jsp
Labels: 👾 feat

#58 feat: 장바구니 기능 #45
  src/main/java/com/lotte/carts/controller/CartController.java
  src/main/java/com/lotte/carts/controller/TempController.java
  src/main/java/com/lotte/carts/dao/CartDao.java
  src/main/java/com/lotte/carts/dao/TempDao.java
  src/main/java/com/lotte/carts/dto/CartItem.java
  src/main/java/com/lotte/carts/dto/CreateCartItem.java
  src/main/java/com/lotte/carts/dto/TempDto.java
  src/main/java/com/lotte/carts/dto/UpdateCartItemCount.java
  src/main/java/com/lotte/carts/dto/request/CartRequest.java
  src/main/java/com/lotte/carts/dto/response/CartResponse.java
  src/main/java/com/lotte/carts/service/CartService.java
  src/main/java/com/lotte/carts/service/TempService.java
  src/main/java/com/lotte/carts/vo/CartItemVO.java
  src/main/java/com/lotte/carts/vo/CartVO.java
  src/main/resources/sqls/Cart.xml
Labels: 👾 feat, 🛠 fix

#60 feat: 상품 상세 페이지 front 생성 #49
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/productdetail.css
  src/main/webapp/productdetail.jsp
  target/lotte_kurly/META-INF/MANIFEST.MF
  target/lotte_kurly/index.jsp
Labels: 👾 feat

#62 feat/crawling 쿠키를 사용하여 오늘 본 상품 구현 #53
  src/main/java/com/lotte/crawling/controller/CrawlingController.java
  src/main/java/com/lotte/crawling/service/CrawlingServiceImpl.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/dto/ProductDto.java
  src/main/java/com/lotte/products/dto/ProductListDto.java
  src/main/resources/sqls/Crawling.xml
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/crawling/crawling.jsp
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/front/images/thumbnail_small.png
  src/main/webapp/front/nav.jsp
  src/main/webapp/front/test.jsp
  src/main/webapp/index.jsp
Labels: 👾 feat

#63 fix: 전체적인 상품리스트 url 수정 #61
  .gitignore
  src/main/java/com/lotte/categories/dao/CategoryDao.java
  src/main/java/com/lotte/categories/dto/CategoryDto.java
  src/main/java/com/lotte/categories/service/CategoryService.java
  src/main/java/com/lotte/categories/service/CategoryServiceImpl.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/resources/sqls/Category.xml
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/product/productlist.jsp
  src/main/webapp/front/header.jsp
  target/lotte_kurly/META-INF/MANIFEST.MF
  target/lotte_kurly/front/header.jsp
Labels: 🛠 fix

#67 feat/localsave 로컬스토리지 사용하여 오늘 본 상품 구현 완료 #53
  src/main/webapp/WEB-INF/views/crawling/crawling.jsp
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/WEB-INF/views/product/productlist.jsp
  src/main/webapp/css/productdetail.css
  src/main/webapp/index.jsp
Labels: 👾 feat

#69 feat: 관리자가 쿠폰을 생성하는 기능 추가 #66 관리자가 하는 역할 admin패키지로 정리 #39
  src/main/Test/com/lotte/products/controller/StatisticControllerTest.java
  src/main/java/com/lotte/accounts/service/AccountServiceImpl.java
  src/main/java/com/lotte/admin/controller/AdminController.java
  src/main/java/com/lotte/admin/controller/StatisticController.java
  src/main/java/com/lotte/admin/dao/AdminDao.java
  src/main/java/com/lotte/admin/dao/StatisticDao.java
  src/main/java/com/lotte/admin/dto/ProductCategoryDto.java
  src/main/java/com/lotte/admin/dto/UserAgeDto.java
  src/main/java/com/lotte/admin/dto/UserGenderDto.java
  src/main/java/com/lotte/admin/dto/UserGradeDto.java
  src/main/java/com/lotte/admin/service/AdminService.java
  src/main/java/com/lotte/admin/service/AdminServiceImpl.java
  src/main/java/com/lotte/admin/service/StatisticService.java
  src/main/java/com/lotte/admin/service/StatisticServiceImpl.java
  src/main/java/com/lotte/coupons/controller/CouponController.java
  src/main/java/com/lotte/coupons/controller/TempController.java
  src/main/java/com/lotte/coupons/dao/CouponDao.java
  src/main/java/com/lotte/coupons/dao/TempDao.java
  src/main/java/com/lotte/coupons/dto/CouponDto.java
  src/main/java/com/lotte/coupons/dto/TempDto.java
  src/main/java/com/lotte/coupons/dto/UserCouponDto.java
  src/main/java/com/lotte/coupons/dto/UserCouponInfo.java
  src/main/java/com/lotte/coupons/service/CouponService.java
  src/main/java/com/lotte/coupons/service/CouponServiceImpl.java
  src/main/java/com/lotte/products/controller/ProductController.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/resources/sqls/Admin.xml
  src/main/resources/sqls/Category.xml
  src/main/resources/sqls/Coupon.xml
  src/main/resources/sqls/Statistic.xml
  src/main/webapp/WEB-INF/views/admin/age-graph.jsp
  src/main/webapp/WEB-INF/views/admin/donut.jsp
  src/main/webapp/WEB-INF/views/admin/gender-graph.jsp
  src/test/java/com/lotte/accounts/controller/AccountControllerTest.java
  src/test/java/com/lotte/db/DBTestServiceTest.java
Labels: 👾 feat, 🌻 refactor

#70 style : 간단회원가입 #12
  src/main/webapp/WEB-INF/views/user/mypage.jsp
  src/main/webapp/css/profile.css
Labels: 👻 style

#75 Feat/crawling detail : 상품 세부 페이지 구축 완료 (데이터 삽입 X) #72
  src/main/java/com/lotte/crawling/service/CrawlingServiceImpl.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/dto/ProductImgCategoryDto.java
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/crawling/crawling.jsp
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/WEB-INF/views/product/productlist.jsp
  src/main/webapp/css/nav.css
  src/main/webapp/css/productdetail.css
  src/main/webapp/front/nav.jsp
  src/main/webapp/index.jsp
Labels: 👾 feat

#80 feat: 주문 결제 기능 API 작성 #55 #77 #79
  src/main/java/com/lotte/accounts/controller/AccountController.java
  src/main/java/com/lotte/accounts/service/AccountService.java
  src/main/java/com/lotte/accounts/service/AccountServiceImpl.java
  src/main/java/com/lotte/carts/dto/CartItem.java
  src/main/java/com/lotte/orders/controller/OrderController.java
  src/main/java/com/lotte/orders/controller/TempController.java
  src/main/java/com/lotte/orders/dao/OrderDao.java
  src/main/java/com/lotte/orders/dao/TempDao.java
  src/main/java/com/lotte/orders/dto/CreateOrder.java
  src/main/java/com/lotte/orders/dto/Order.java
  src/main/java/com/lotte/orders/dto/OrderCartItem.java
  src/main/java/com/lotte/orders/dto/OrderDetail.java
  src/main/java/com/lotte/orders/dto/OrderUserDetail.java
  src/main/java/com/lotte/orders/dto/TempDto.java
  src/main/java/com/lotte/orders/dto/request/OrderRequest.java
  src/main/java/com/lotte/orders/dto/response/OrderResponse.java
  src/main/java/com/lotte/orders/exception/ErrorResponse.java
  src/main/java/com/lotte/orders/exception/NotEnoughStockAfterPayment.java
  src/main/java/com/lotte/orders/exception/NotEnoughStocks.java
  src/main/java/com/lotte/orders/service/OrderService.java
  src/main/java/com/lotte/orders/service/TempService.java
  src/main/java/com/lotte/orders/vo/OrderProductVO.java
  src/main/java/com/lotte/orders/vo/OrderVO.java
  src/main/resources/sqls/Cart.xml
  src/main/resources/sqls/Category.xml
  src/main/resources/sqls/Order.xml
  target/lotte_kurly/META-INF/MANIFEST.MF
  target/lotte_kurly/front/header.jsp
  target/lotte_kurly/index.jsp
Labels: 👾 feat

#81 feat: Admin 메인화면에 그래프들 추가하기 #21
  src/main/java/com/lotte/admin/controller/AdminPageController.java
  src/main/java/com/lotte/admin/controller/StatisticController.java
  src/main/java/com/lotte/admin/dao/StatisticDao.java
  src/main/java/com/lotte/admin/dto/TotalOrderDto.java
  src/main/java/com/lotte/admin/service/StatisticService.java
  src/main/java/com/lotte/admin/service/StatisticServiceImpl.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/resources/sqls/Statistic.xml
  src/main/webapp/WEB-INF/views/admin/admin-list.jsp
  src/main/webapp/WEB-INF/views/admin/admin-main.jsp
  src/main/webapp/WEB-INF/views/admin/age-graph.jsp
  src/main/webapp/WEB-INF/views/admin/axis.jsp
  src/main/webapp/WEB-INF/views/admin/donut.jsp
  src/main/webapp/WEB-INF/views/admin/gender-graph.jsp
  src/main/webapp/WEB-INF/views/admin/member.jsp
  src/main/webapp/WEB-INF/views/admin/product.jsp
  src/main/webapp/css/admin.css
  target/lotte_kurly/META-INF/MANIFEST.MF
  target/lotte_kurly/index.jsp
Labels: 👾 feat

#84 feat: 마이페이지 #83
  src/main/java/com/lotte/users/controller/UserController.java
  src/main/java/com/lotte/users/dao/UserDao.java
  src/main/java/com/lotte/users/service/UserService.java
  src/main/java/com/lotte/users/service/UserServiceImpl.java
  src/main/resources/sqls/User.xml
  src/main/webapp/WEB-INF/views/user/mypage.jsp
Labels: 👾 feat

#86 fix: 스크립트 충돌
  src/main/webapp/WEB-INF/views/test.jsp
  src/main/webapp/css/header.css
  src/main/webapp/css/nav.css
  src/main/webapp/front/header.jsp
  src/main/webapp/front/nav.jsp
  src/main/webapp/main.jsp
Labels: 🛠 fix

#89 feat : 리뷰 생성
  src/main/java/com/lotte/reviews/controller/ReviewPageController.java
  src/main/java/com/lotte/reviews/dto/ReviewDto.java
  src/main/java/com/lotte/reviews/dto/ReviewInsertDto.java
  src/main/java/com/lotte/reviews/service/ReviewServiceImpl.java
  src/main/resources/sqls/Review.xml
  src/main/webapp/WEB-INF/views/crawling.jsp
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
Labels: 👾 feat

#90 feat : 주문서 페이지 생성 #82
  src/main/webapp/ordersheet.css
  src/main/webapp/ordersheet.jsp
Labels: 👾 feat

#91 feat: 리뷰생성 #88
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
Labels: 👾 feat

#93 feat: 프로덕트 디테일 불러오기 #72
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/productdetail.jsp
Labels: 👾 feat

#97 Revert "feat: 베스트 상품 기능,상품 리스트 소팅전부 구현 #92"
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/dto/ProductBestDto.java
  src/main/java/com/lotte/products/dto/ProductListDto.java
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/product/bestproductlist.jsp
  src/main/webapp/WEB-INF/views/product/productlist.jsp
  src/main/webapp/front/header.jsp
  src/main/webapp/index.jsp
  target/lotte_kurly/META-INF/MANIFEST.MF
  target/lotte_kurly/front/header.jsp
Labels: 👾 feat

#98 fix: 헤더수정
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/webapp/front/header.jsp
Labels: 🛠 fix

#100 feat : 주문서 페이지 결제하기 버튼 추가 #82 , favicon 설정 #99
  src/main/webapp/front/header.jsp
  src/main/webapp/front/images/favicon.png
  src/main/webapp/ordersheet.css
  src/main/webapp/ordersheet.jsp
  target/lotte_kurly/META-INF/MANIFEST.MF
Labels: 👾 feat

#104 feat: footer #103
  src/main/webapp/css/footer.css
  src/main/webapp/front/footer.jsp
  src/main/webapp/front/header.jsp
  src/main/webapp/index.jsp
  target/lotte_kurly/META-INF/MANIFEST.MF
Labels: 👾 feat

#106 feat: 결제 모달, 계좌 잔액 차감
  src/main/java/com/lotte/accounts/controller/AccountController.java
  src/main/java/com/lotte/accounts/dao/AccountDao.java
  src/main/java/com/lotte/accounts/dto/request/AccountBuyRequest.java
  src/main/java/com/lotte/accounts/service/AccountService.java
  src/main/java/com/lotte/accounts/service/AccountServiceImpl.java
  src/main/java/com/lotte/orders/controller/OrderPageController.java
  src/main/java/com/lotte/orders/dao/OrderDao.java
  src/main/java/com/lotte/orders/dto/Order.java
  src/main/java/com/lotte/orders/dto/OrderCartItem.java
  src/main/java/com/lotte/orders/service/OrderService.java
  src/main/resources/sqls/Account.xml
  src/main/resources/sqls/Order.xml
  src/main/webapp/WEB-INF/views/cart/cart.jsp
  src/main/webapp/WEB-INF/views/order/orderdetail.jsp
  src/main/webapp/WEB-INF/views/order/orderlist.jsp
  src/main/webapp/WEB-INF/views/order/ordersheet.jsp
  src/main/webapp/css/ordersheet.css
  src/main/webapp/front/header.jsp
  src/main/webapp/index.jsp
  src/main/webapp/js/cart.js
  src/main/webapp/js/orderdetail.js
  src/main/webapp/js/orderlist.js
  src/main/webapp/js/ordersheet.js
  target/lotte_kurly/META-INF/MANIFEST.MF
  target/lotte_kurly/index.jsp
Labels: 👾 feat

#110 feat: 메인 페이지 추가 및 메인페이지 위치 변경 #109
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/dto/ProductListMainBestDto.java
  src/main/java/com/lotte/products/dto/ProductListMainDiscountDto.java
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/product/main.jsp
  src/main/webapp/index.jsp
  target/lotte_kurly/META-INF/MANIFEST.MF
  target/lotte_kurly/index.jsp
Labels: 👾 feat

#113 feat/reviewDevelop 상품 디테일에 ajax사용하여 review 구현 #88
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/css/productdetail.css
  target/lotte_kurly/META-INF/MANIFEST.MF
  target/lotte_kurly/index.jsp
Labels: 👾 feat, 💡 idea

#114 feat : 리뷰 페이지 css 완성 #111
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/css/productdetail.css
Labels: 👾 feat

#115 feat: 결제 잔액 차감 기능 #79
  src/main/java/com/lotte/accounts/controller/AccountController.java
  src/main/java/com/lotte/accounts/dto/request/AccountBuyRequest.java
  src/main/resources/sqls/Account.xml
  src/main/webapp/js/ordersheet.js
Labels: 👾 feat

#120 fix: 베스트상품 리스트 상세페이지 안넘어가는거 해결
  src/main/webapp/WEB-INF/views/product/bestproductlist.jsp
Labels: 🛠 fix

#122 feat: 결제 및 주문 처리 기능
  src/main/java/com/lotte/orders/controller/OrderController.java
  src/main/java/com/lotte/orders/dao/OrderDao.java
  src/main/java/com/lotte/orders/dto/request/OrderRequest.java
  src/main/java/com/lotte/orders/exception/NotEnoughStockAfterPayment.java
  src/main/java/com/lotte/orders/service/OrderService.java
  src/main/resources/sqls/Order.xml
  src/main/webapp/js/ordersheet.js
Labels: 👾 feat

#121 feat: 상품 등록과 재고 업데이트
  src/main/java/com/lotte/admin/controller/AdminController.java
  src/main/java/com/lotte/admin/controller/AdminPageController.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/dao/ProductDao.java
  src/main/java/com/lotte/products/dto/ProductDto.java
  src/main/java/com/lotte/products/dto/ProductListDto.java
  src/main/java/com/lotte/products/service/ProductService.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/resources/sqls/Product.xml
  src/main/webapp/WEB-INF/views/admin/admin-list.jsp
  src/main/webapp/WEB-INF/views/admin/admin-main.jsp
  src/main/webapp/WEB-INF/views/admin/product-list.jsp
  src/main/webapp/WEB-INF/views/admin/product-register.jsp
  src/main/webapp/WEB-INF/views/admin/product-update.jsp
Labels: 👾 feat, 🌻 refactor

#123 Feat/jsp
  src/main/java/com/lotte/carts/dto/CartItem.java
  src/main/resources/sqls/Cart.xml
  src/main/webapp/WEB-INF/views/cart/cart.jsp
  src/main/webapp/css/cart.css
  src/main/webapp/css/footer.css
  src/main/webapp/front/footer.jsp
  src/main/webapp/js/cart.js
Labels: 👾 feat

#124 feat : 결제 모달 css 완성 #116
  src/main/webapp/WEB-INF/views/order/ordersheet.jsp
  src/main/webapp/css/ordersheet.css
Labels: 👾 feat

#126 refactoring: 의미없는 alert와 System.out.println제거 #35
  src/main/Test/com/lotte/products/controller/StatisticControllerTest.java
  src/main/java/com/lotte/admin/controller/AdminController.java
  src/main/java/com/lotte/crawling/service/CrawlingServiceImpl.java
  src/main/java/com/lotte/products/controller/ProductPageController.java
  src/main/java/com/lotte/products/service/ProductServiceImpl.java
  src/main/java/com/lotte/reviews/controller/ReviewPageController.java
  src/main/java/com/lotte/users/service/UserServiceImpl.java
  src/main/webapp/WEB-INF/views/admin/admin-main.jsp
  src/main/webapp/WEB-INF/views/admin/product-list.jsp
  src/main/webapp/WEB-INF/views/admin/product-register.jsp
  src/main/webapp/WEB-INF/views/admin/product-update.jsp
  src/main/webapp/WEB-INF/views/crawling/crawling.jsp
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  target/lotte_kurly/META-INF/MANIFEST.MF
Labels: 🌻 refactor

#132 feat: 카트 담기 로고 메인보내기
  src/main/webapp/WEB-INF/views/product/bestproductlist.jsp
  src/main/webapp/WEB-INF/views/product/main.jsp
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/WEB-INF/views/product/productlist.jsp
  src/main/webapp/front/header.jsp
Labels: 👾 feat

#133 feat : productlist.css 수정
  src/main/webapp/css/productlist.css
  target/lotte_kurly/META-INF/MANIFEST.MF
Labels: 👾 feat

#138 feat : 관리자 페이지 css 수정 #137
  src/main/webapp/WEB-INF/views/admin/admin-main.jsp
  src/main/webapp/WEB-INF/views/admin/product-list.jsp
  src/main/webapp/WEB-INF/views/admin/product-register.jsp
  src/main/webapp/WEB-INF/views/admin/product-update.jsp
  src/main/webapp/css/admin.css
Labels: 👾 feat

#139 fix: test
  src/main/java/com/lotte/users/controller/UserController.java
  src/main/java/com/lotte/users/dao/UserDao.java
  src/main/java/com/lotte/users/service/UserService.java
  src/main/java/com/lotte/users/service/UserServiceImpl.java
  src/main/resources/sqls/User.xml
  src/main/webapp/WEB-INF/views/user/mypage.jsp
  src/main/webapp/front/header.jsp
  src/main/webapp/productdetail.jsp
  target/lotte_kurly/META-INF/MANIFEST.MF
Labels: 🛠 fix

#150 feat: 작은 수정 #35
  src/main/resources/sqls/Statistic.xml
  src/main/webapp/WEB-INF/views/admin/admin-main.jsp
  src/main/webapp/WEB-INF/views/admin/product-list.jsp
  src/main/webapp/WEB-INF/views/admin/product-register.jsp
  src/main/webapp/WEB-INF/views/admin/product-update.jsp
  target/lotte_kurly/META-INF/MANIFEST.MF
Labels: 👻 style

#164 fix: 비회원 장바구니 기능 제한
  src/main/java/com/lotte/carts/controller/CartController.java
  src/main/java/com/lotte/carts/service/CartService.java
  src/main/java/com/lotte/carts/service/CartServiceImpl.java
  src/main/java/com/lotte/exception/ErrorResponse.java
  src/main/java/com/lotte/orders/controller/OrderController.java
  src/main/java/com/lotte/orders/controller/OrderPageController.java
  src/main/java/com/lotte/orders/service/OrderService.java
  src/main/java/com/lotte/orders/service/OrderServiceImpl.java
  src/main/webapp/WEB-INF/views/product/bestproductlist.jsp
  src/main/webapp/WEB-INF/views/product/main.jsp
  src/main/webapp/WEB-INF/views/product/productdetail.jsp
  src/main/webapp/WEB-INF/views/product/productlist.jsp
  src/main/webapp/front/header.jsp
  src/main/webapp/js/cart.js
Labels: 🛠 fix
